#!/usr/local/bin/perl
use strict;
use Getopt::Std;

our %ARGV;
our %opts;
my (%PREFIX, %SUFFIX);
my ($PREFIX, $SUFFIX);

getopts('h', \%opts);
sub usage {
    my $FILE = __FILE__;
    print <<HELP;
  setup config.ph, looking up the directory, and find
  prefix and suffix of image files

synopsis:
    $0  [-h] directory
where
    -h  this help
HELP
}

if ($opts{'h'}) { usage(); exit;}

my $DIR = $ARGV[0];

opendir(DIR, $DIR) || die "   *** Problem opening Directory: $DIR $!\n";

while (readdir(DIR)) {
    next if (/^\./);
    next if (/^\.\./);
    my ($name, $suffix)  = split ('\.');
    my ($prefix, $rest)  = split ('_', $name);
#    print $prefix . ' -- ' . $rest .' -- ' . $suffix . "\n";
    $PREFIX{$prefix}++;
    $SUFFIX{$suffix}++;
}
close (DIR);

open(CONFIG , "> config.ph") || die "Problem opening file to write: $!\n";

foreach my $i (keys(%PREFIX)) {
    print $i . ' -- ' . $PREFIX{$i},"\n";
    $PREFIX = $i;
}

foreach my $i (keys(%SUFFIX)) {
    print $i . ' -- ' . $SUFFIX{$i},"\n";
    $SUFFIX = $i;
}

while (<DATA>) {
    if (   /\$c::PREF = /) {
	print CONFIG '   $c::PREF = '. "'" . $PREFIX . "_' ;\n";
    }
    elsif (/\$c::SUF = /) {
	print CONFIG '   $c::SUF = '.  "'" . $SUFFIX . "' ;\n";    }
    else {
	print CONFIG;
    }
}
__END__

# $Id: config.ph,v 1.3 2009/11/07 02:57:32 makoto Exp $
# sample for config.ph
  $c::PREF = 'IMG_';
  $c::SUF = 'JPEG';
#  $c::TITLE = 'L5Bj';
#  $c::COMMENT = 'Entry Page comment';
